# Generated by Django 4.2.3 on 2023-08-04 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pagos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pago",
            name="total_horas",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
