# Generated by Django 4.2.3 on 2023-08-17 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pagos", "0002_pago_total_horas"),
    ]

    operations = [
        migrations.AddField(
            model_name="pago",
            name="notas",
            field=models.TextField(blank=True, null=True),
        ),
    ]
