# Generated by Django 4.2.3 on 2023-10-02 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0003_alter_valorhorausuario_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="valorhorausuario",
            options={
                "ordering": ("desde",),
                "verbose_name_plural": "valores hora de usuarios",
            },
        ),
    ]
