# Generated by Django 4.2.3 on 2023-07-23 22:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("hours", "0002_alter_hours_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hours",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
