# Generated by Django 4.2.3 on 2023-08-04 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("liquidaciones", "0001_initial"),
        ("hours", "0003_alter_hours_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="hours",
            options={"verbose_name_plural": "horas"},
        ),
        migrations.AddField(
            model_name="hours",
            name="liquidacion",
            field=models.ForeignKey(
                blank=True,
                help_text="Liquidacion a la que pertenece esta hora. Se carga sola al liquidarse a finde mes",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hours",
                to="liquidaciones.liquidacion",
            ),
        ),
    ]
