# Generated by Django 4.2.3 on 2023-08-17 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("liquidaciones", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Adelanto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "moneda",
                    models.CharField(
                        choices=[
                            ("AR", "Peso Argentino"),
                            ("USD", "Dolar Usa"),
                            ("EUR", "Euro"),
                        ],
                        default="AR",
                        max_length=3,
                    ),
                ),
                ("total", models.DecimalField(decimal_places=2, max_digits=20)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "liquidacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adelantos",
                        to="liquidaciones.liquidacion",
                    ),
                ),
            ],
        ),
    ]
